# 1. Introduction to PyTorch, a Deep Learning Library

Self-driving cars, smartphones, search engines... Deep learning is now everywhere. Before you begin building complex models, you will become familiar with PyTorch, a deep learning framework. You will learn how to manipulate tensors, create PyTorch data structures, and build your first neural network in PyTorch with linear layers.

## 1.1 Import Libraries

In [1]:
import torch
import numpy as np

## 1.2 User Variables

In [ ]:
# No user variables here

# 2. Exercises

## 2.1 Getting started with PyTorch tensors

### Description

Tensors are PyTorch's core data structure and the foundation of deep learning. They're similar to NumPy arrays but have unique features.

Here you have a Python list named ``temperatures`` containing daily readings from two weather stations. Try converting this into a tensor!

### Instructions

* Begin by importing ``torch``.
* Create a tensor from the Python list ``temperatures``.

In [2]:
# Import PyTorch
import torch

temperatures = [[72, 75, 78], [70, 73, 76]]

# Create a tensor from temperatures
temp_tensor = torch.tensor(temperatures)

print(temp_tensor)

tensor([[72, 75, 78],
        [70, 73, 76]])


### Analogy of Tensors vs NumPy Array to a restaurant

* NumPy array is like a plain, traditional buffet tables
    * Mutable - Modify the dishes directly (add/remove/change the ingredients)
    * Works well on a single table (CPU), but is not suitable for GPUs
    * Does not leverage special equipments (like a kitchen with dedicated chef or special tools)
* Tensors are like high-tech gourmet kitchen with advanced appliances
    * Immutable
    * Can handle larger, more complex dishes very efficiently, especially if its connected to a faster stove (GPU or TPUI (Tensor Processing Unit by Google))
    * Multiple tasks/dishes in parallel, supports special cooking techniques (automatic differentiation) used by pro chefs (deep learning models)

### Compare memory differences between NumPy arrays vs Tensor

In [3]:
import sys

In [4]:
test_list = [i for i in range(10000)]
test_numpy_arr = np.array(test_list)
test_torch_tensor = torch.tensor(test_list)

list_size = sys.getsizeof(test_list) + sum(sys.getsizeof(item) for item in test_list)
numpy_size = test_numpy_arr.nbytes
torch_size = test_torch_tensor.element_size() * test_torch_tensor.nelement()

print(f"List: {list_size} | NumPy: {numpy_size} | Tensor: {torch_size}")

List: 365176 | NumPy: 80000 | Tensor: 80000


The memory difference mentioned earlier refers to the entire object and runtime environment, not just the raw data buffer:

* Tensors have additional metadata, state, and management overhead related to GPU support, autograd (automatic differentiation), and efficient memory handling for deep learning.
* Tensors can also allocate memory on GPUs, requiring different memory bookkeeping beyond just the data buffer.
* NumPy arrays are simpler, focused on CPU memory only, with less overhead but no GPU or autograd capabilities.

So, when checking just the raw data size, they look the same. The actual memory footprint difference arises from tensor-specific features and how they manage memory beyond just storing data. That overhead is not included in simple ``.nbytes`` or ``.element_size()`` * ``nelement()`` calculations.

## 2.2 Checking and adding tensors

### Description

While collecting temperature data, you notice the readings are off by two degrees. Add two degrees to the ``temperatures`` tensor after verifying its shape and data type with ``torch`` to ensure compatibility with the ``adjustment`` tensor.

The ``torch`` library and the ``temperatures`` tensor are loaded for you.

### Instructions

* Display the shape of the ``adjustment`` tensor.
* Display the data type of the ``adjustment`` tensor.
* Add the ``temperatures`` and ``adjustment`` tensors.

In [5]:
temperatures = temp_tensor

In [6]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

# Display the shape of the adjustment tensor
print("Adjustment shape:", adjustment.shape)

# Display the type of the adjustment tensor
print("Adjustment type:", adjustment.dtype)

print("Temperatures shape:", temperatures.shape)
print("Temperatures type:", temperatures.dtype)

Adjustment shape: torch.Size([2, 3])
Adjustment type: torch.int64
Temperatures shape: torch.Size([2, 3])
Temperatures type: torch.int64


In [7]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

# Add the temperatures and adjustment tensors
corrected_temperatures = temperatures + adjustment
print("Corrected temperatures:", corrected_temperatures)

Corrected temperatures: tensor([[74, 77, 80],
        [72, 75, 78]])


## 2.3 Linear layer network

### Description

Neural networks often contain many layers, but most of them are linear layers. Understanding a single linear layer helps you grasp how they work before adding complexity.

Apply a linear layer to an input tensor and observe the output.

### Instructions

* Create a ``Linear`` layer that takes 3 features as input and returns 2 outputs.
* Pass ``input_tensor`` through the linear layer.

In [8]:
import torch
import torch.nn as nn

input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

# Create a Linear layer
linear_layer = nn.Linear(
                         in_features=3, 
                         out_features=2
                         )

# Pass input_tensor through the linear layer
output = linear_layer(input_tensor)

print(output)

tensor([[-0.1443,  0.3594]], grad_fn=<AddmmBackward0>)


### Illustration

![Linear Neural Network Example](../images/nn_linear_example.png)

## 2.4 Quiz: Understanding weights

### Description

In a linear model, weights and biases play a crucial role in determining how inputs are transformed into outputs. Understanding their function is key to building effective neural networks. Now, let's test your understanding!

### Instructions

What is the role of weights in a neural network?

### Answer

Weights determine how much influence each input has on the neuron's output. Weights adjust the contribution of each input feature, allowing the network to learn patterns and make better predictions.

## 2.5 Your first neural network

### Description

It's time for you to implement a small neural network containing two linear layers in sequence.

### Instructions

* Add a container for stacking layers in sequence.

In [9]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Create a container for stacking linear layers
model = nn.Sequential(nn.Linear(8, 4),
                nn.Linear(4, 1)
                )

output = model(input_tensor)
print(output)

tensor([[2.9240]], grad_fn=<AddmmBackward0>)


## 2.6 Stacking linear layers

### Description

Nice work building your first network with two linear layers. Let's stack some more layers. Remember that a neural network can have as many hidden layers as we want, provided the inputs and outputs line up.

This network is designed to ingest the following input:

```py
input_tensor = torch.Tensor(
    [[2, 7, 9, 5, 3]]
    )
```

### Instructions

* Reorder the items provided to create a neural network with three hidden layers and an output of size 2.

In [10]:
input_tensor = torch.Tensor([[2, 7, 9, 5, 3]])

model = nn.Sequential(
    nn.Linear(5, 20),
    nn.Linear(20, 14),
    nn.Linear(14, 3),
    nn.Linear(3, 2)
)

## 2.7 Counting the number of parameters

### Description

Deep learning models are famous for having a lot of parameters. With more parameters comes more computational complexity and longer training times, and a deep learning practitioner must know how many parameters their model has.

In this exercise, you'll first calculate the number of parameters manually. Then, you'll verify your result using the ``.numel()`` method.

### Instructions

* Q1. Manually calculate the number of parameters of the model below. How many does it have? Use the console as a calculator.
```py
model = nn.Sequential(nn.Linear(9, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))
```
* Use ``.numel()`` to confirm your manual calculation by iterating through the model's parameters to updating the ``total`` variable.

### Answer: 

* Answer1: `53`.
    * First Layer (9,4):
        * Weights: 9 inputs x 4 outputs = 36 parameters
        * Biases: 4 parameters (same as outputs)
        * First Layer paraneters: 40+4 = 40 parameters
    * Second Layer (4,2):
        * Weights: 4 inputs x 2 outputs = 8 parameters
        * Biases: 2 parameters (same as outputs)
        * Second Layer paraneters: 8+2 = 10 parameters
    * Third / Output Layer (2,1):
        * Weights: 2 inputs x 1 output = 2 parameters
        * Biases: 1 parameter (same as output)
        * Output Layer paraneters: 2+1 = 3 parameters
    * 40 + 10 + 3 = 53 parameters

In [12]:
model = nn.Sequential(nn.Linear(9, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))

total = 0
for parameter in model.parameters():
    total += parameter.numel()
print(total)

53


In [13]:
import torch.nn as nn

model = nn.Sequential(nn.Linear(9, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))

total = 0

# Calculate the number of parameters in the model
for p in model.parameters():
  total += p.numel()
  
print(f"The number of parameters in the model is {total}")

The number of parameters in the model is 53
